[package]
name = "nmstate-clib"
description = "Nmstate C binding"
version = "2.2.0"
authors = ["Gris Ge <fge@redhat.com>"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "nmstate"
path = "lib.rs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
nmstate = { path = "../lib", default-features = false }
libc = "0.2.74"
serde_json = "1.0"
log = "0.4.17"
serde = { version = "1.0.137", features = ["derive"] }
once_cell = "1.12.0"

[features]
default = ["query_apply", "gen_conf"]
query_apply = ["nmstate/query_apply"]
gen_conf = ["nmstate/gen_conf"]
